# Generated by Django 4.2.10 on 2024-03-02 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время старта')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Стоимость')),
                ('max_group_capacity', models.PositiveIntegerField(default=4, verbose_name='Максимальное число учащихся')),
                ('min_group_capacity', models.PositiveSmallIntegerField(default=3, verbose_name='Минимальное число учащихся')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_products', related_query_name='own_product', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_waiting_access', models.BooleanField(default=False, verbose_name='Ожидает доступ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_users', related_query_name='access_user', to='product.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_products', related_query_name='access_product', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ пользователя к продукту',
                'verbose_name_plural': 'Доступы пользователей к продуктам',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('video_url', models.CharField(max_length=2100, verbose_name='Ссылка на видео')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', related_query_name='lesson', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', related_query_name='group', to='product.product', verbose_name='Группа')),
                ('users', models.ManyToManyField(related_name='user_groups', related_query_name='user_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
